# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Chia Yong Kang
logo:               # Logo image URL
email:              chiayongkang@hotmail.com
description:        My thoughts and Projects :)
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://maxima-jekyll.aspirethemes.com' # The base hostname & protocol for your site
github_username:    ExtremelySunnyYK
twitter_username:   ExtremelySunnYK
linkedin_username : 'yong-kang-chia-66b225154'
resume : https://extremelysunnyyk.github.io/YongKang_chia_resume.pdf.pdf


markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

